### ISSUE TITLE
Add native I/O support for numpy arrays as image types

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#28]
Basically Gmic's `run()` method should accept 1 or several `nparray` for its `images=` parameter.
[Numpy type official documentation page](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

We want as low-level optimization as possible, grabbing the numpy buffers arrays, and without any extra binary dependency.

Workflows yielding a `nparray` for an image are typicall from [scikit-image](https://scikit-image.org/) and [PIL/Pillow](https://pillow.readthedocs.io/en/stable/).

De-interlacing and re-interlacing at the `gmic.run()'s` input and output are necessary.

**TODO list**

- [x] if numpy is not importable, all of the following will fail with an ImportError or ModuleNotFound exception; no ugly segfault.

~~- [ ] `GmicImage(data=a_numpy_array """no dimensions info, they are inferred from the object's shape""") -> GmicImage`~~
~~- [ ] `GmicImage(ndarray)` unit testing~~

- [x] `GmicImage.to_numpy_array(self, astype=numpy.float32: numpy.dtype, interleave=True: bool) -> numpy.ndarray`
- [x] `GmicImage().to_numpy_array()` unit testing

- [x] `GmicImage.from_numpy_array(cls, obj: numpy.ndarray, deinterleave=True: bool) -> GmicImage()`
- [x] `GmicImage().from_numpy_array()` unit testing

~~- [ ] `gmic.run(images=List<numpy.ndarray>|List<GmicImage>) -> in place change of `images=List<same type as inputted>` ; same behaviour for gmic.Gmic(...) or gmic.Gmic(...).run(...)`~~
~~- [ ] `gmic.run()` (& gmic instance alternatives) unit testing~~

- [x] add numpy support C ifdefs with setup.py togglable flags

~~- [ ] add complex numbers numpy array dtype support~~
~~- [ ] unit test complex numbers support~~

~~- [ ] potential memory leaks care~~

- [x] add numpy as a build flag stored in `gmic.__build__` string 
- [x] have [numpy examples](https://github.com/myselfhimself/gmic-py/tree/numpy_io/examples/numpy) running without any issue

**Comment by myselfhimself** [comment]
OpenCV inspiration code for any type of pixel size to CImg: https://github.com/dtschump/CImg/blob/master/plugins/cvMat.h

**Comment by myselfhimself** [comment]
Per-pixel size is in ndarray.dtype
```
>>> im.dtype
dtype('uint8')
```

**Comment by myselfhimself** [comment]
Work is in progress for `uint8` pixel-`dtype` 2D RGB nparrays, the binding still crashes.. I will post back when this works. After then, we shall be lenient with other `dtype`s (uint16 etc..) and be tolerant with other shapes: 1D, 2D, 3D, 1-255 channels by point.

**Comment by myselfhimself** [comment]
Design notes:

## INPUT
For inputting of `numpy.ndarray`s, the path is pretty clear: on the fly conversion in `GmicImage(data:numpy.ndarray)` constructor or `gmic.run(images:List<numpy.ndarray>|numpy.ndarray)`
The input numpy.ndarray `dtype` will be read, and data will be cast to GmicImage's T type (float).
By itself, the code will tolerant to mixed-types `images` list ie. having `GmicImage` and `numpy.ndarray` elements, without extra coding needed.
Envisioned acceptable channel value `dtype`s are : 1bit, 8bit signed/unsigned/int/float, 16bit signed/unsigned/int/float, 32bit signed/unsigned/int/float.
[(The list of numpy dtypes is here.)](https://docs.scipy.org/doc/numpy/user/basics.types.html)

## OUTPUT
- For outputting, if any `numpy.ndarray` was given as input, despite any possible mixed existence of `GmicImage`/`numpy.ndarray` as mentioned above, all images will be converted to `numpy.ndarray` will be handed for all outputs.
- A boolean flag will allow for setting the output `dtype`, but by default it will be Gmic's, that is some `float32` ([using the numpy.array.astype() method as a convenience for the user](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html)). 
- The `images` list will be rewritten in-place, but its contents are first removed (dereferenced) then filled out-of-place; that is, the incoming numpy arrays are not edited at all, and new numpy arrays are provided instead.
- Example `.run()` signature:
```
from numpy import array
from copy import deepcopy
my_numpy_arrays =[array(...), array()...]
numpy_arrays_copy = deepcopy(my_numpy_arrays)
gmic.run(images=my_numpy_arrays, command="blur", numpy_output_dtype='uint16')
assert my_numpy_arrays != numpy_arrays_copy # True
```

**Comment by myselfhimself** [comment]
Single item images `run(images=aNumpyNdarray, command="...")` objects will be edited in place though

**Comment by myselfhimself** [comment]
as far as 2D RGB images are concerned, these POCs are ready but uncomitted yet:
- uint8 `numpy.ndarray` input with deinterlacing
- float32 `numpy.ndarray` output with reinterlacing, pipeable using `numpy.ndarray.astype(dtype=numpy.uint8|numpy.uint16 etc..)`

The design is changing slightly:
```
if numpy is not importable, all of the following will fail with an ImportError or ModuleNotFound exception; no ugly segfault.
GmicImage(data=a_numpy_array """no dimensions info, they are inferred from the object's shape""") -> GmicImage
GmicImage().to_numpy_array(astype=numpy.float32: numpy.dtype, interlace=True: bool) -> numpy.ndarray
GmicImage.from_numpy_array(obj: numpy.ndarray, deinterlace=True: bool) -> GmicImage()
gmic.run(images=List<numpy.ndarray, GmicImage> """ie. a possibly mixed-types list""", command="...", to_numpy_array=False:bool, to_numpy_as_type=numpy.float32: numpy.dtype, to_numpy_interlace=True: bool, to_numpy_deinterlace=False: bool) #same behaviour for gmic.Gmic(...) or gmic.Gmic(...).run(...)
```

Those interlace and deinterlace flags could be logical-bit-&'ed maybe... Let us be imperfect for now.

**Comment by myselfhimself** [comment]
Work on the class method "GmicImage.from_numpy_array(obj: numpy.ndarray, deinterlace=True: bool) -> GmicImage()" has started... it will be hopefully stable this week

**Comment by myselfhimself** [comment]
Work on the class method `GmicImage.from_numpy_array(obj: numpy.ndarray, deinterlace=True: bool) -> GmicImage()` has started... it will be hopefully stable this week

**Comment by myselfhimself** [comment]
Working full time on this now

**Comment by myselfhimself** [comment]
libgmic 2.9.0 which was just released is targetted

**Comment by myselfhimself** [comment]
interleaving and dtype checking+conversion should not happen in any of the gmic.run() input/output images processing loop which is quite long already, but in the from_numpy() to_numpy() methods.

**Comment by myselfhimself** [comment]
There are a few unit tests already regarding numpy support, but I am lost in them.

Here is a simple handmade test that shows OK support for the numpy ndarray output: (image.png is a lena sample picture)

```
import gmic
import PIL
import PIL.Image
from numpy import asarray, array_equal
from matplotlib import pyplot

i = PIL.Image.open('image.png')
ii = asarray(i)

l = []
gmic.run("sp lena", l)
ll = l[0].to_numpy_array(interleave=True, astype=int)
array_equal(ll,ii)

pyplot.imshow(ll)
pyplot.show()
pyplot.imshow(ii)
pyplot.show()
```

let me see for simple numpy ndarray input hand testing...

**Comment by myselfhimself** [comment]
the testing scenario now works OK a bit further (except that dtype variety is not yet covered):
```
# TEST 1: numpy(interleaved)->pyplot_display(interleaved)->gmic_from_nparray(deinterleaved)->gmic_display(deinterleaved)
import gmic
import PIL
import PIL.Image
from numpy import asarray, array_equal
from matplotlib import pyplot

gmic.run("sp lena output image.png")
i = PIL.Image.open('image.png') # Lena sample
ii = asarray(i)

l = []
gmic.run("sp lena", l)
ll = l[0].to_numpy_array(interleave=True, astype=int)
array_equal(ll,ii) # True

pyplot.imshow(ll)
pyplot.show() # Lena in good colors, dimensions and orientation

pyplot.imshow(ii)
pyplot.show() # Lena in good colors, dimensions and orientation

j = gmic.GmicImage.from_numpy_array(ll, deinterleave=True)
gmic.run("display", j) # Lena in good colors, dimensions and orientation

jj = gmic.GmicImage.from_numpy_array(ii, deinterleave=True)
gmic.run("display", jj) # TODO STRANGE IMAGE
```

**Comment by myselfhimself** [comment]
Progress on above empirical test by extending it thanks to to_numpy_array and from_numpy_array simplification and solidification. See below. Sold unit tests will be written. Will check boxes in the above message when those upcoming tests pass for each method.
Oustanding work is also for `GmicImage(numpy.ndarray)` initialization (code removed for now) and  `gmic.run(images=List<numpy.ndarray>)` (started) calls which are comfort-related and could maybe be ifdef-ed for later toggling and maintainability... Those calls will also need proper unit testing...
Depending on time, complex numbers could be in for this numpy-support release, for now only boolean-int-float scalars are to be supported.
 
```
# TEST 1: numpy(interleaved)->pyplot_display(interleaved)->gmic_from_nparray(deinterleaved)->gmic_display(deinterleaved)
import gmic
import PIL
import PIL.Image
import numpy
from numpy import asarray, array_equal
from matplotlib import pyplot

gmic.run("sp lena output image.png")
i = PIL.Image.open('image.png') # Lena sample
ii = asarray(i)
print(ii.shape) #(512, 512, 3)
print(ii.dtype) #uint8

l = []
gmic.run("sp lena", l)
ll = l[0].to_numpy_array(interleave=True, astype=numpy.uint8, squeeze_shape=True)
array_equal(ll,ii) # True
print(ll.shape) #(512, 512, 3)
print(ll.dtype) #uint8

pyplot.imshow(ll)
pyplot.show() # Lena in good colors, dimensions and orientation

pyplot.imshow(ii)
pyplot.show() # Lena in good colors, dimensions and orientation

j = gmic.GmicImage.from_numpy_array(ll, deinterleave=True)
gmic.run("display", j) # Lena in good colors, dimensions and orientation
"""
[gmic]-1./ Display image [0] = '[unnamed]', from point (256,256,0).
[0] = '[unnamed]':
  size = (512,512,1,3) [3072 Kio of floats].
  data = (225,225,223,223,225,225,225,223,225,223,223,223,(...),78,78,78,77,91,80,79,89,77,79,79,82).
  min = 8, max = 251, mean = 128.241, std = 58.9512, coords_min = (457,60,0,1), coords_max = (425,20,0,0).
"""

jj = gmic.GmicImage.from_numpy_array(ii, deinterleave=True)
gmic.run("display", jj) # Lena in good colors, dimensions and orientation
"""
[gmic]-1./ Display image [0] = '[unnamed]', from point (256,256,0).
[0] = '[unnamed]':
  size = (512,512,1,3) [3072 Kio of floats].
  data = (225,225,223,223,225,225,225,223,225,223,223,223,(...),78,78,78,77,91,80,79,89,77,79,79,82).
  min = 8, max = 251, mean = 128.241, std = 58.9512, coords_min = (457,60,0,1), coords_max = (425,20,0,0).
"""
```

```
# TEST 2: numpy(deinterleaved)->gmic_from_nparray(deinterleaved)->gmic_display(deinterleaved)
import gmic
import PIL
import PIL.Image
from numpy import asarray, array_equal

gmic.run("sp lena output image.png")
i = PIL.Image.open('image.png')
ii = asarray(i)
print(ii.shape) # (512, 512, 3)
print(ii.dtype) # uint8

l = []
gmic.run("sp lena", l)
ll = l[0].to_numpy_array(interleave=False, astype=int, squeeze_shape=True) # default astype=float32, default squeeze_shape=True
print(ll.shape) # (512, 512, 3)
print(ll.dtype) # int64
array_equal(ll,ii) # False; uint8 vs. int64 match but deinterleave vs interleave unmatch

j = gmic.GmicImage.from_numpy_array(ll, deinterleave=False)
gmic.run("display", j) # Lena in good orientation, color, size
"""
[gmic]-1./ Display image [0] = '[unnamed]', from point (256,256,0).
[0] = '[unnamed]':
  size = (512,512,1,3) [3072 Kio of floats].
  data = (225,225,223,223,225,225,225,223,225,223,223,223,(...),78,78,78,77,91,80,79,89,77,79,79,82).
  min = 8, max = 251, mean = 128.241, std = 58.9512, coords_min = (457,60,0,1), coords_max = (425,20,0,0).
"""

jj = gmic.GmicImage.from_numpy_array(ii, deinterleave=True)
gmic.run("display", jj)  # Lena in good orientation, color, size
"""
[gmic]-1./ Display image [0] = '[unnamed]', from point (256,256,0).
[0] = '[unnamed]':
  size = (512,512,1,3) [3072 Kio of floats].
  data = (225,225,223,223,225,225,225,223,225,223,223,223,(...),78,78,78,77,91,80,79,89,77,79,79,82).
  min = 8, max = 251, mean = 128.241, std = 58.9512, coords_min = (457,60,0,1), coords_max = (425,20,0,0).
"""
```
```

**Comment by myselfhimself** [comment]
Note that `GmicImage.to_numpy_array()` has a new default parameter `squeeze_shape=True`, where the default shape that G'MIC likes` (w,h,d,c) ` is clear from its dimensions `=1`, eg. 2d RGB images in shape `(512,512,1,3)` will have a `(512,512,3)` shape instead, which matplot will not refuse for displaying.

**Comment by myselfhimself** [comment]
Updated TODO list in topmost message above

**Comment by myselfhimself** [comment]
- a GmicImage() can now be initialized with an empty `data` buffer parameter, it will be filled with zeros according to the provided image dimensions `(w,h,d,c)`

**Comment by myselfhimself** [comment]
**Architecture tiny refactoring needed...**
`GmicImage(numpy.ndarray)` and `GmicImage.from_numpy_array(numpy.ndarray)` are in a spaghetti situation with reciprocal dependency, where the numpy array to GmicImage's conversion logic belongs mostly in the latter method. Right now AST errors and segfaults have been showing up since I finished programming the former constructor morphism.
=> Rewrite both methods to disentangle this...

`GmicImage(data: numpy.ndarray|bytes, deinterleave=False: bool) -> GmicImage` should be the new constructor signature and standalone from any public method.
`GmicImage.from_numpy_array(data: numpy.ndarray, deinterleave=True: bool) -> GmicImage` is unchanged but should just do a `return GmicImage(data, deinterleave)`

**Comment by techtonik** [comment]
if numpy arrays method of processing data is more efficient, maybe propose that format in G'MIC forum? https://discuss.pixls.us/c/software/gmic/10

**Comment by jfolz** [comment]
If I understand this correctly: G'MIC expects images in `(w,h,d,c)` order, whereas basically everyone else does either `(h,w,d,c)` (mostly d=1, used by CPU-code) or `(c,d,h,w)` (mostly d=1, used by GPU-code).
`ndarray.transpose` can be used with `ndarray.copy` to deal with this. Copy is necessary if G'MIC requires the array is contiguous in the given order. If strided arrays are supported, then not :)
If you don't want a binary dependency to numpy you can also use the [memoryview API](https://docs.python.org/3/c-api/memoryview.html). The [Py_buffer](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer) struct gives you direct access to data and shape info.

**Comment by myselfhimself** [comment]
Hello @jfolz and @techtonik you are super super lovely!!! (meaning it)
Right now I have transposed by hand in multiple for loops instead of using `ndarray.transpose`.
I do have spotted the memoryview API, as it is used within the [PyCImg project](https://github.com/d0m3nik/pycimg/) (G'mic's image type is just a #define of CImg's image type), except that the latter targets a very old CImg version...
I want to sit down again on this topic, because we are very close to completion thanks to numpy's `ndarray` handy methods such as `as_type()` and `transpose()` (although gmic has a `permute` command). Strided array are not supported in G'MIC to my knowledge.
The Python binding right nows tries to import numpy and complains if it is not there, and then uses memoryview-like reading technique from a pointer exposed by numpy for C-binders, so there is no binary dependency.
@techtonik thank you for having divulgated the existence of this binding on the G'MIC forum, faster than we intended to communicate on this. We will make an official announcement this month hopefully...

**Comment by myselfhimself** [comment]
I have reduced the scope of this issue at the very top, in order to release a solid `numpy.ndarray` <-> `GmicImage` I/O earlier.
No implicit conversion from `numpy.ndarray` to `GmicImage` will be done anywhere anymore. This will help clean the spaghetti and library users will have to use `GmicImage.from_numpy_array()` and `GmicImage.to_numpy_array()` by hand themselves.
Those simple `from_` and `to_` methods can give future inspiration for I/O towards other libraries and image types.

**Comment by myselfhimself** [comment]
Potential memory leaks care is slated for 2.9.2. It is a general gmic-py topic actually, not just the numpy I/O support.

**Comment by techtonik** [comment]
@myselfhimself is there a memory format that is the most suited for image processing? Like the one that can be handled by CPU efficiently? I thought that `numpy` proposes something like this.

**Comment by jfolz** [comment]
For serial operation on CPU `H,W,C` is usually fine. Number of channels is typically quite small compared to height and width. Operations in the channel dimension can be the innermost loop and be unrolled if you know how many channels there will be. So you're operating on data that's right next to each other and load/store operations can be reordered as required.
For SIMD or GPU it's more complicated, but generally `C,H,W` is better. It's easier and faster to fill registers from memory in chunks. I haven't dared to program SIMD myself yet ([so many intrinsics...](https://software.intel.com/sites/landingpage/IntrinsicsGuide)), but you can probably get similar speed if you queue up multiple SIMD operations at once (e.g. 3 for RGB images), but that uses more registers.

**Comment by myselfhimself** [comment]
Dropped 32bits and sunsetting python3.5 builds #49 #50 in order to make gmic-py 2.9.1 tests work..

**Comment by myselfhimself** [comment]
will be finished in #59 // numpy support subpart
