### ISSUE TITLE
Add libgmic 2.9.0 support

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#35]
- [x] add alpha quality #28 numpy support
- [x] #31 proper JSON output (to file or string as a gmic image) of filters will be important and to test
- [x] #36 Add gmic-py vs. gmic-cli I/O parity tests (non-regression)
- [x] #37 Throw a GmicException instead of Exception
- [x] #31 add GmicImage._data_str read-only dynamic member to intepret GmicImage floats as str
- [x] Allow initialization of an empty image with a None data buffer: `gmic.GmicImage(None,[w,h,d,c])`
- [x] #14 PPM unit test
- [x] embed version and config options in __version__ and __build__
- [x] #23 beautified c/c++ and python using clang-format and black
- [x] #32 auto-load personal and update .gmic files on startup?
- [x] manylinux2014+manylinux2010 libcurl bundling fix
- [x] #6 macosx
- [x] #27 build_tools.bash fruity improvement
- [x] #40 make release on git tag push event only
- [x] #39 use optimization flags for release

**Comment by myselfhimself** [comment]
Slight encoding issue in JSON output processing:
>>> a = []
>>> gmic.run("parse_gui blur*,json", images=a)
>>> a
[<gmic.GmicImage object at 0x7fe2f35c8d80 with _data address at 0x78a4160, w=1 h=90 d=1 s=1 shared=0>]
>>> a[0]._data
b'\x00\x00\xf6B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xccB\x00\x00\xdeB\x00\x00\xe4B\x00\x00\xdaB\x00\x00\xc2B\x00\x00\xe8B\x00\x00\xbeB\x00\x00\xecB\x00\x00\xcaB\x00\x00\xe4B\x00\x00\xe6B\x00\x00\xd2B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\x08B\x00\x00\xceB\x00\x00\xdaB\x00\x00\xd2B\x00\x00\xc6B\x00\x00\xbeB\x00\x00\xd4B\x00\x00\xe6B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\xbeB\x00\x00DB\x00\x008B\x00\x00@B\x00\x00\x08B\x00\x000B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xceB\x00\x00\xdaB\x00\x00\xd2B\x00\x00\xc6B\x00\x00\xbeB\x00\x00\xecB\x00\x00\xcaB\x00\x00\xe4B\x00\x00\xe6B\x00\x00\xd2B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\x08B\x00\x00HB\x00\x008B\x00\x00dB\x00\x008B\x00\x00@B\x00\x00\x08B\x00\x000B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xc6B\x00\x00\xc2B\x00\x00\xe8B\x00\x00\xcaB\x00\x00\xceB\x00\x00\xdeB\x00\x00\xe4B\x00\x00\xd2B\x00\x00\xcaB\x00\x00\xe6B\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\xb6B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\xbaB\x00\x00 A\x00\x00\xfaB\x00\x00 A'
>>> a[0]._data.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 2: invalid start byte
>>> a[0]._data.decode('us-ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 2: ordinal not in range(128)
>>> a[0]._data.decode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 2: ordinal not in range(128)
>>> gmic.run("parse_gui blur*,json output out.json", images=a)
>>> open("out.json").read()
'[\n{\n  "image": {\n    "name": "/tmp/m3112XAZ.png",\n    "format": "PNG",\n    "formatDescription": "Portable Network Graphics",\n    "mimeType": "image/png",\n    "class": "PseudoClass",\n    "geometry": {\n      "width": 1,\n      "height": 90,\n      "x": 0,\n      "y": 0\n    },\n    "units": "Undefined",\n    "type": "Grayscale",\n    "endianess": "Undefined",\n    "colorspace": "Gray",\n    "depth": 8,\n    "baseDepth": 8,\n    "channelDepth": {\n      "gray": 8\n    },\n    "pixels": 90,\n    "channelStatistics": {\n      "gray": {\n        "min": 10,\n        "max": 125,\n        "mean": 74.9889,\n        "standardDeviation": 9630.98,\n        "kurtosis": -1.58568,\n        "skewness": -0.317196,\n        "entropy": 0.923418\n      }\n    },\n    "colormapEntries": 256,\n    "colormap": [\n        "#000000","#010101","#020202","#030303","#040404",\n      "#050505","#060606","#070707","#080808","#090909",\n      "#0A0A0A","#0B0B0B","#0C0C0C","#0D0D0D","#0E0E0E",\n      "#0F0F0F","#101010","#111111","#121212","#131313",\n      "#141414","#151515","#161616","#171717","#181818",\n      "#191919","#1A1A1A","#1B1B1B","#1C1C1C","#1D1D1D",\n      "#1E1E1E","#1F1F1F","#202020","#212121","#222222",\n      "#232323","#242424","#252525","#262626","#272727",\n      "#282828","#292929","#2A2A2A","#2B2B2B","#2C2C2C",\n      "#2D2D2D","#2E2E2E","#2F2F2F","#303030","#313131",\n      "#323232","#333333","#343434","#353535","#363636",\n      "#373737","#383838","#393939","#3A3A3A","#3B3B3B",\n      "#3C3C3C","#3D3D3D","#3E3E3E","#3F3F3F","#404040",\n      "#414141","#424242","#434343","#444444","#454545",\n      "#464646","#474747","#484848","#494949","#4A4A4A",\n      "#4B4B4B","#4C4C4C","#4D4D4D","#4E4E4E","#4F4F4F",\n      "#505050","#515151","#525252","#535353","#545454",\n      "#555555","#565656","#575757","#585858","#595959",\n      "#5A5A5A","#5B5B5B","#5C5C5C","#5D5D5D","#5E5E5E",\n      "#5F5F5F","#606060","#616161","#626262","#636363",\n      "#646464","#656565","#666666","#676767","#686868",\n      "#696969","#6A6A6A","#6B6B6B","#6C6C6C","#6D6D6D",\n      "#6E6E6E","#6F6F6F","#707070","#717171","#727272",\n      "#737373","#747474","#757575","#767676","#777777",\n      "#787878","#797979","#7A7A7A","#7B7B7B","#7C7C7C",\n      "#7D7D7D","#7E7E7E","#7F7F7F","#808080","#818181",\n      "#828282","#838383","#848484","#858585","#868686",\n      "#878787","#888888","#898989","#8A8A8A","#8B8B8B",\n      "#8C8C8C","#8D8D8D","#8E8E8E","#8F8F8F","#909090",\n      "#919191","#929292","#939393","#949494","#959595",\n      "#969696","#979797","#989898","#999999","#9A9A9A",\n      "#9B9B9B","#9C9C9C","#9D9D9D","#9E9E9E","#9F9F9F",\n      "#A0A0A0","#A1A1A1","#A2A2A2","#A3A3A3","#A4A4A4",\n      "#A5A5A5","#A6A6A6","#A7A7A7","#A8A8A8","#A9A9A9",\n      "#AAAAAA","#ABABAB","#ACACAC","#ADADAD","#AEAEAE",\n      "#AFAFAF","#B0B0B0","#B1B1B1","#B2B2B2","#B3B3B3",\n      "#B4B4B4","#B5B5B5","#B6B6B6","#B7B7B7","#B8B8B8",\n      "#B9B9B9","#BABABA","#BBBBBB","#BCBCBC","#BDBDBD",\n      "#BEBEBE","#BFBFBF","#C0C0C0","#C1C1C1","#C2C2C2",\n      "#C3C3C3","#C4C4C4","#C5C5C5","#C6C6C6","#C7C7C7",\n      "#C8C8C8","#C9C9C9","#CACACA","#CBCBCB","#CCCCCC",\n      "#CDCDCD","#CECECE","#CFCFCF","#D0D0D0","#D1D1D1",\n      "#D2D2D2","#D3D3D3","#D4D4D4","#D5D5D5","#D6D6D6",\n      "#D7D7D7","#D8D8D8","#D9D9D9","#DADADA","#DBDBDB",\n      "#DCDCDC","#DDDDDD","#DEDEDE","#DFDFDF","#E0E0E0",\n      "#E1E1E1","#E2E2E2","#E3E3E3","#E4E4E4","#E5E5E5",\n      "#E6E6E6","#E7E7E7","#E8E8E8","#E9E9E9","#EAEAEA",\n      "#EBEBEB","#ECECEC","#EDEDED","#EEEEEE","#EFEFEF",\n      "#F0F0F0","#F1F1F1","#F2F2F2","#F3F3F3","#F4F4F4",\n      "#F5F5F5","#F6F6F6","#F7F7F7","#F8F8F8","#F9F9F9",\n      "#FAFAFA","#FBFBFB","#FCFCFC","#FDFDFD","#FEFEFE",\n      "#FFFFFF"\n    ],\n    "renderingIntent": "Undefined",\n    "gamma": 0.454545,\n    "backgroundColor": "#FFFFFF",\n    "borderColor": "#DFDFDF",\n    "matteColor": "#BDBDBD",\n    "transparentColor": "#000000",\n    "interlace": "None",\n    "intensity": "Undefined",\n    "compose": "Over",\n    "pageGeometry": {\n      "width": 1,\n      "height": 90,\n      "x": 0,\n      "y": 0\n    },\n    "dispose": "Undefined",\n    "iterations": 0,\n    "compression": "Zip",\n    "quality": 100,\n    "orientation": "Undefined",\n    "properties": {\n      "date:create": "2020-03-31T19:30:32+02:00",\n      "date:modify": "2020-03-31T19:30:32+02:00",\n      "png:IHDR.bit-depth-orig": "8",\n      "png:IHDR.bit_depth": "8",\n      "png:IHDR.color-type-orig": "0",\n      "png:IHDR.color_type": "0 (Grayscale)",\n      "png:IHDR.interlace_method": "0 (Not interlaced)",\n      "png:IHDR.width,height": "1, 90",\n      "signature": "cc91ccd3c6a2c26bfdfe1e0a6dee97c5ddde0525771c140e990c9fcfc3d8a953"\n    },\n    "artifacts": {\n      "filename": "/tmp/m3112XAZ.png",\n      "quality": "100"\n    },\n    "tainted": false,\n    "filesize": "4096B",\n    "numberPixels": "90",\n    "pixelsPerSecond": "90000000000000B",\n    "userTime": "0.000u",\n    "elapsedTime": "0:01.000",\n    "version": "ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org"\n  }\n}\n]'

**Comment by myselfhimself** [comment]
> Slight encoding issue in JSON output processing:
> 
> > > > a = []
> > > > gmic.run("parse_gui blur*,json", images=a)
> > > > a
> > > > [<gmic.GmicImage object at 0x7fe2f35c8d80 with _data address at 0x78a4160, w=1 h=90 d=1 s=1 shared=0>]
> > > > a[0]._data
> > > > b'\x00\x00\xf6B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xccB\x00\x00\xdeB\x00\x00\xe4B\x00\x00\xdaB\x00\x00\xc2B\x00\x00\xe8B\x00\x00\xbeB\x00\x00\xecB\x00\x00\xcaB\x00\x00\xe4B\x00\x00\xe6B\x00\x00\xd2B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\x08B\x00\x00\xceB\x00\x00\xdaB\x00\x00\xd2B\x00\x00\xc6B\x00\x00\xbeB\x00\x00\xd4B\x00\x00\xe6B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\xbeB\x00\x00DB\x00\x008B\x00\x00@B\x00\x00\x08B\x00\x000B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xceB\x00\x00\xdaB\x00\x00\xd2B\x00\x00\xc6B\x00\x00\xbeB\x00\x00\xecB\x00\x00\xcaB\x00\x00\xe4B\x00\x00\xe6B\x00\x00\xd2B\x00\x00\xdeB\x00\x00\xdcB\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\x08B\x00\x00HB\x00\x008B\x00\x00dB\x00\x008B\x00\x00@B\x00\x00\x08B\x00\x000B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\x08B\x00\x00\xc6B\x00\x00\xc2B\x00\x00\xe8B\x00\x00\xcaB\x00\x00\xceB\x00\x00\xdeB\x00\x00\xe4B\x00\x00\xd2B\x00\x00\xcaB\x00\x00\xe6B\x00\x00\x08B\x00\x00hB\x00\x00\x00B\x00\x00\xb6B\x00\x00 A\x00\x00\x00B\x00\x00\x00B\x00\x00\xbaB\x00\x00 A\x00\x00\xfaB\x00\x00 A'
> > > > a[0]._data.decode('utf-8')
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 2: invalid start byte
> > > > a[0]._data.decode('us-ascii')
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 2: ordinal not in range(128)
> > > > a[0]._data.decode('ascii')
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 2: ordinal not in range(128)
> > > > gmic.run("parse_gui blur*,json output out.json", images=a)
> > > > open("out.json").read()
> > > > '[\n{\n  "image": {\n    "name": "/tmp/m3112XAZ.png",\n    "format": "PNG",\n    "formatDescription": "Portable Network Graphics",\n    "mimeType": "image/png",\n    "class": "PseudoClass",\n    "geometry": {\n      "width": 1,\n      "height": 90,\n      "x": 0,\n      "y": 0\n    },\n    "units": "Undefined",\n    "type": "Grayscale",\n    "endianess": "Undefined",\n    "colorspace": "Gray",\n    "depth": 8,\n    "baseDepth": 8,\n    "channelDepth": {\n      "gray": 8\n    },\n    "pixels": 90,\n    "channelStatistics": {\n      "gray": {\n        "min": 10,\n        "max": 125,\n        "mean": 74.9889,\n        "standardDeviation": 9630.98,\n        "kurtosis": -1.58568,\n        "skewness": -0.317196,\n        "entropy": 0.923418\n      }\n    },\n    "colormapEntries": 256,\n    "colormap": [\n        "#000000","#010101","#020202","#030303","#040404",\n      "#050505","#060606","#070707","#080808","#090909",\n      "#0A0A0A","#0B0B0B","#0C0C0C","#0D0D0D","#0E0E0E",\n      "#0F0F0F","#101010","#111111","#121212","#131313",\n      "#141414","#151515","#161616","#171717","#181818",\n      "#191919","#1A1A1A","#1B1B1B","#1C1C1C","#1D1D1D",\n      "#1E1E1E","#1F1F1F","#202020","#212121","#222222",\n      "#232323","#242424","#252525","#262626","#272727",\n      "#282828","#292929","#2A2A2A","#2B2B2B","#2C2C2C",\n      "#2D2D2D","#2E2E2E","#2F2F2F","#303030","#313131",\n      "#323232","#333333","#343434","#353535","#363636",\n      "#373737","#383838","#393939","#3A3A3A","#3B3B3B",\n      "#3C3C3C","#3D3D3D","#3E3E3E","#3F3F3F","#404040",\n      "#414141","#424242","#434343","#444444","#454545",\n      "#464646","#474747","#484848","#494949","#4A4A4A",\n      "#4B4B4B","#4C4C4C","#4D4D4D","#4E4E4E","#4F4F4F",\n      "#505050","#515151","#525252","#535353","#545454",\n      "#555555","#565656","#575757","#585858","#595959",\n      "#5A5A5A","#5B5B5B","#5C5C5C","#5D5D5D","#5E5E5E",\n      "#5F5F5F","#606060","#616161","#626262","#636363",\n      "#646464","#656565","#666666","#676767","#686868",\n      "#696969","#6A6A6A","#6B6B6B","#6C6C6C","#6D6D6D",\n      "#6E6E6E","#6F6F6F","#707070","#717171","#727272",\n      "#737373","#747474","#757575","#767676","#777777",\n      "#787878","#797979","#7A7A7A","#7B7B7B","#7C7C7C",\n      "#7D7D7D","#7E7E7E","#7F7F7F","#808080","#818181",\n      "#828282","#838383","#848484","#858585","#868686",\n      "#878787","#888888","#898989","#8A8A8A","#8B8B8B",\n      "#8C8C8C","#8D8D8D","#8E8E8E","#8F8F8F","#909090",\n      "#919191","#929292","#939393","#949494","#959595",\n      "#969696","#979797","#989898","#999999","#9A9A9A",\n      "#9B9B9B","#9C9C9C","#9D9D9D","#9E9E9E","#9F9F9F",\n      "#A0A0A0","#A1A1A1","#A2A2A2","#A3A3A3","#A4A4A4",\n      "#A5A5A5","#A6A6A6","#A7A7A7","#A8A8A8","#A9A9A9",\n      "#AAAAAA","#ABABAB","#ACACAC","#ADADAD","#AEAEAE",\n      "#AFAFAF","#B0B0B0","#B1B1B1","#B2B2B2","#B3B3B3",\n      "#B4B4B4","#B5B5B5","#B6B6B6","#B7B7B7","#B8B8B8",\n      "#B9B9B9","#BABABA","#BBBBBB","#BCBCBC","#BDBDBD",\n      "#BEBEBE","#BFBFBF","#C0C0C0","#C1C1C1","#C2C2C2",\n      "#C3C3C3","#C4C4C4","#C5C5C5","#C6C6C6","#C7C7C7",\n      "#C8C8C8","#C9C9C9","#CACACA","#CBCBCB","#CCCCCC",\n      "#CDCDCD","#CECECE","#CFCFCF","#D0D0D0","#D1D1D1",\n      "#D2D2D2","#D3D3D3","#D4D4D4","#D5D5D5","#D6D6D6",\n      "#D7D7D7","#D8D8D8","#D9D9D9","#DADADA","#DBDBDB",\n      "#DCDCDC","#DDDDDD","#DEDEDE","#DFDFDF","#E0E0E0",\n      "#E1E1E1","#E2E2E2","#E3E3E3","#E4E4E4","#E5E5E5",\n      "#E6E6E6","#E7E7E7","#E8E8E8","#E9E9E9","#EAEAEA",\n      "#EBEBEB","#ECECEC","#EDEDED","#EEEEEE","#EFEFEF",\n      "#F0F0F0","#F1F1F1","#F2F2F2","#F3F3F3","#F4F4F4",\n      "#F5F5F5","#F6F6F6","#F7F7F7","#F8F8F8","#F9F9F9",\n      "#FAFAFA","#FBFBFB","#FCFCFC","#FDFDFD","#FEFEFE",\n      "#FFFFFF"\n    ],\n    "renderingIntent": "Undefined",\n    "gamma": 0.454545,\n    "backgroundColor": "#FFFFFF",\n    "borderColor": "#DFDFDF",\n    "matteColor": "#BDBDBD",\n    "transparentColor": "#000000",\n    "interlace": "None",\n    "intensity": "Undefined",\n    "compose": "Over",\n    "pageGeometry": {\n      "width": 1,\n      "height": 90,\n      "x": 0,\n      "y": 0\n    },\n    "dispose": "Undefined",\n    "iterations": 0,\n    "compression": "Zip",\n    "quality": 100,\n    "orientation": "Undefined",\n    "properties": {\n      "date:create": "2020-03-31T19:30:32+02:00",\n      "date:modify": "2020-03-31T19:30:32+02:00",\n      "png:IHDR.bit-depth-orig": "8",\n      "png:IHDR.bit_depth": "8",\n      "png:IHDR.color-type-orig": "0",\n      "png:IHDR.color_type": "0 (Grayscale)",\n      "png:IHDR.interlace_method": "0 (Not interlaced)",\n      "png:IHDR.width,height": "1, 90",\n      "signature": "cc91ccd3c6a2c26bfdfe1e0a6dee97c5ddde0525771c140e990c9fcfc3d8a953"\n    },\n    "artifacts": {\n      "filename": "/tmp/m3112XAZ.png",\n      "quality": "100"\n    },\n    "tainted": false,\n    "filesize": "4096B",\n    "numberPixels": "90",\n    "pixelsPerSecond": "90000000000000B",\n    "userTime": "0.000u",\n    "elapsedTime": "0:01.000",\n    "version": "ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org"\n  }\n}\n]'

fixed

**Comment by myselfhimself** [comment]
- Releasing now 2.9.0 with macos, linux support using -Ofast -flto compiler optimization (2x-4x speed-up); numpy from_ to_ support is there undercover in "alpha" stage.

- I am planning to add solid numpy support in 2.9.1. Numpy will be useful for images I/O in image formatting libraries like Pillow... pygame maybe.

- Windows support is still unknown.

**Comment by myselfhimself** [comment]
Not slating windows support #5 for libgmic 2.9.0

**Comment by myselfhimself** [comment]
Done

**Comment by myselfhimself** [comment]
related parse_gui fix: https://github.com/dtschump/gmic/issues/256
