### ISSUE TITLE
Add libgmic 2.9.2 support

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#46]
- [x]  quite solid #59 numpy, PIL, scikit support
- [x] more documentation on doc/ readthedocs or in the examples/ directory
- [x] merge back into master branch #44
- [x] ensure 2.9.1 network command behaviour change does not impact tests
- [x] add Jupyter / IPython console output redirection and image display fallback back-end #63 #64 and document #65

Not slating Windows support for this release for now

**Comment by myselfhimself** [comment]
Still 4x occurences of pytests to write (or skip..):
```
(gmicpy290numpy) jd@jd-ThinkPad-T400:~/Productions/GMIC/gmic-py$ grep pytest gmicpy.cpp 
        // TODO pytest this
            // TODO pytest this
            // TODO pytest this
            // TODO pytest this

```

**Comment by myselfhimself** [comment]
2.9.1 stable will skipped in favour of very transient 2.9.2
2.9.4 will be released this week

**Comment by myselfhimself** [comment]
the "TODO pytest this" tests implementation task has been moved to #85 and is now unrelated to any release version

**Comment by myselfhimself** [comment]
Released
